answerly/urls.py
from django.contrib import admin
from django.urls import path, include

import qanda.urls
import user.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(qanda.urls, namespace='qanda')),
    path('user/', include(user.urls, namespace='user')),
]

qanda/urls.py
from django.urls import path

from qanda.views import (AskQuestionView, QuestionDetailView,
                         CreateAnswerView, UpdateAnswerAcceptanceView,
                         DailyQuestionListView, TodayQuestionListView,
                         SearchView)

app_name = 'qanda'
urlpatterns = [
    path('ask/',
         AskQuestionView.as_view(),
         name='ask'),

    path('q/<int:pk>',
         QuestionDetailView.as_view(),
         name="question-detail"),

    path('q/<int:pk>/answer',
         CreateAnswerView.as_view(),
         name="answer-question"),

    path('q/search',
         SearchView.as_view(),
         name='question-search'),

    path('a/<int:pk>/accept',
         UpdateAnswerAcceptanceView.as_view(),
         name="update-answer-acceptance"),

    path('daily/<int:year>/<int:month>/<int:day>/',
         DailyQuestionListView.as_view(),
         name="daily-questions"),

    path('',
         TodayQuestionListView.as_view(),
         name="index")
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from user.views import RegisterView

app_name = 'user'
urlpatterns = [
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('register', RegisterView.as_view(), name="register"),
]

qanda/models.py
from django.conf import settings
from django.db import models
from django.urls.base import reverse
from django.contrib.postgres.search import SearchVector


class QuestionManager(models.Manager):
    def find_questions(self, query):
        qs = self.get_queryset()
        return qs.annotate(
            search=SearchVector('title', 'question')
        ).filter(search=query)


class Question(models.Model):
    title = models.CharField(max_length=140)
    question = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    objects = QuestionManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("qanda:question-detail", kwargs=dict(pk=self.id))

    def can_accept_answers(self, user):
        return user == self.user


class Answer(models.Model):
    answer = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(to=Question,
                                 on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )

user/models.py
from django.db import models

# Create your models here.

qanda/forms.py
from django import forms
from django.contrib.auth import get_user_model

from qanda.models import Question, Answer


class BaseForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )


class QuestionForm(BaseForm):
    class Meta:
        model = Question
        fields = ('title', 'question', 'user')


class AnswerForm(BaseForm):
    question = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Question.objects.all(),
        disabled=True
    )

    class Meta:
        model = Answer
        fields = ('answer', 'user', 'question')


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False
    )

    class Meta:
        model = Answer
        fields = ('accepted',)

qanda/views.py
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseBadRequest
from django.http import HttpResponseRedirect
from django.views.generic import (CreateView, DetailView,
                                  UpdateView, DayArchiveView,
                                  RedirectView, TemplateView)

from qanda.forms import QuestionForm, AnswerForm, AnswerAcceptanceForm
from qanda.models import Question, Answer


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = 'qanda/ask.html'

    def get_initial(self):
        return {
            'user': self.request.user.id
        }

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Question(
                question=form.cleaned_data['question'],
                title=form.cleaned_data['title']
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()


class QuestionDetailView(DetailView):
    model = Question

    ACCEPT_FORM = AnswerAcceptanceForm(initial={'accepted': True})
    REJECT_FORM = AnswerAcceptanceForm(initial={'accepted': False})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            'answer_form': AnswerForm(initial={
                'user': self.request.user.id,
                'question': self.object.id
            })
        })
        if self.object.can_accept_answers(self.request.user):
            ctx.update({
                'accept_form': self.ACCEPT_FORM,
                'reject_form': self.REJECT_FORM
            })
        return ctx


class CreateAnswerView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    template_name = 'qanda/create_answer.html'

    def get_initial(self):
        return {
            'question': self.get_question().id,
            'user': self.request.user.id
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            return super().form_valid(form)
        elif action == 'PREVIEW':
            ctx = self.get_context_data(preview=form.cleaned_data['answer'])
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

    def get_question(self):
        return Question.objects.get(pk=self.kwargs['pk'])


class UpdateAnswerAcceptanceView(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_invalid(self, form):
        return HttpResponseRedirect(
            redirect_to=self.object.question.get_absolute_url()
        )


class DailyQuestionListView(DayArchiveView):
    queryset = Question.objects.all()
    date_field = 'created'
    month_format = '%m'
    allow_empty = True


class TodayQuestionListView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse(
            'qanda:daily-questions',
            kwargs={
                'day': today.day,
                'month': today.month,
                'year': today.year
            }
        )


class SearchView(TemplateView):
    template_name = 'qanda/search.html'

    def get_context_data(self, **kwargs):
        query = self.request.GET.get('q', None)
        ctx = super().get_context_data(query=query, **kwargs)
        if query:
            results = Question.objects.find_questions(query)
            ctx['hits'] = results
        return ctx

user/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView


class RegisterView(CreateView):
    template_name = 'user/register.html'
    form_class = UserCreationForm

qanda/templates/qanda/ask.html
{% extends 'base.html' %}

{% load markdownify %}
{% load crispy_forms_tags %}

{% block title %} Ask a question {% endblock %}

{% block body %}
<div class="col-md-12">
    <h1>Ask a question</h1>
    {% if preview %}
    <div class="container"> 
        <div class="card question-preview">
            <div class="card-header">
                Question Preview 
            </div>
            <div class="card-body">
                <h1 class="card-title">{{ preview.title }}</h1>
                {{ preview.question| markdownify }}
            </div>
        </div>
    </div>
    {% endif %}
    <form method="post">
        {{ form| crispy }}
        {% csrf_token %}
        <button class="btn btn-primary" type="submit" name="action" value="PREVIEW">Preview</button>
        <button class="btn btn-primary" type="submit" name="action" value="SAVE">Ask!</button>
    </form>
</div>
{% endblock %}

qanda/templates/qanda/common/display_question.html
{% load markdownify %}

<div class="question">
    <div class="meta col-sm-12">
        <h1>{{ question.title }}</h1>
        <span class="text-muted">Asked by {{question.user}} on {{ question.created|date:'Y-m-d'}} {{question.created|date:'H:i'}}</span>
    </div>
    <div class="body lead col-sm-12">
        {{ question.question|markdownify }}
    </div>
</div>

qanda/templates/qanda/common/list_answers.html
{% load markdownify %}

<div class="container">
    <h3>Answers</h3>
    <ul class="list-unstyled answers">
        {% for answer in question.answer_set.all %}
            <li class="answer row">
                <div class="col-sm-3 col-m2-2 text-center">
                    {% if answer.accepted %}
                        <span class="badge badge-pill badge-success">Accepted</span>
                    {% endif %}
                    {% if answer.accepted and reject.form %}
                        <form action="{% url 'qanda:update-answer-acceptance' pk=answer.id %}" method="post">
                            {% csrf_token %}
                            {{ reject_form }}
                            <button type="submit" class="btn btn-link">
                                <i class="fas fa-times">Reject</i>
                            </button>
                        </form>
                    {% elif accept_form %}
                        <form action="{% url 'qanda:update-answer-acceptance' pk=answer.id %}" method="post">
                            {% csrf_token %}
                            {{ accept_answer }}
                            <button type="submit" class="btn btn-link" title="Accept answer">
                                <i class="fas fa-times" aria-hidden="true">Accept</i>
                            </button>
                        </form>
                    {% endif %}
                </div>
                <div class="col-sm-9 col-md-10">
                    <div class="body">{{ answer.answer| markdownify }}</div>
                    <div class="meta font-weight-light">
                        Answered by {{ answer.user }} on {{answer.created|date:'Y-m-d'}} {{answer.created|date:'H:i'}}
                    </div>
                </div>
            </li>
            {% empty %}
            <li class="answer">No answers yet!</li>
        {% endfor %}
    </ul>
</div>

qanda/templates/qanda/common/post_answer.html
{% load crispy_forms_tags %}

<div class="col-sm-12">
    <h3>Post your answers</h3>
    <form method="post"action="{% url 'qanda:answer-question' pk=question.id %}">
        {{ answer_form| crispy}}
        {% csrf_token %}
        <button class="btn btn-primary" type="submit", value="PREVIEW", name="action">Preview</button>
        <button class="btn btn-primary" type="submit", value="SAVE", name="action">Answer</button>
    </form>
</div>

qanda/templates/qanda/create_answer.html
{% extends 'base.html' %}
{% load markdownify %}

{% block body %}
    {% include 'qanda/common/display_question.html' %}
        {% if preview %}
        <div class="container">
            <div class="card question-preview">
                <div class="card-header">Answer preview</div>
                <div class="card-body">
                    {{ preview|markdownify }}
                </div>
            </div>
        </div>
        {% endif %}
    {% include 'qanda/common/post_answer.html' with answer_form=form %}
{% endblock %}

qanda/templates/qanda/question_archive_day.html
{% extends 'base.html' %}

{% block title %}Questions on {{ day }} {% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1>Highest Voted Questions of {{ day }}</h1>
    <div class="list-group mb-2">
        {% for question in object_list %}
            <a href="{{ question.get_absolute_url }}"
               class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ question }}</h5>
                <small>{{ question.votes }}</small>
            </div>
            <p class="mb-1">
            {{ question.question }}
            </p>
            <small>
                by
                {{ question.user }}
                on {{ question.created|date:'Y-m-d'}} {{question.created|date:'H:i'}}
            </small>
            </a>
            {% empty %}
                <span>No questons for today</span>
        {% endfor %}
    </div>
<div>
<ul class="pagination">
    {% if previous_day %}
    <li class="page-item">
        <a class="page-link"
            href="{% url 'qanda:daily-questions' year=previous_day.year month=previous_day.month day=previous_day.day %}">
            Previous Day
        </a>
    </li>
    {% endif %}
    {% if next_day %}
    <li class="page-item">
        <a class="page-link" 
            href="{% url 'qanda:daily-questions' year=next_day.year month=next_day.month day=next_day.day %}">
            Next Day
        </a>
    </li>
    {% endif %}
</ul>
</div>
</div>
{% endblock %}

qanda/templates/qanda/question_detail.html
{% extends 'base.html' %}

{% block title %}{{ question.title }} - {{ block.super }}{% endblock %}

{% block body %}
{% include "qanda/common/display_question.html" %}
{% include "qanda/common/list_answers.html" %}
{% if user.is_authenticated %}
    {% include "qanda/common/post_answer.html" %}
{% else %}
    <div>Login to post answers.</div>
{% endif %}
{% endblock %}
    

qanda/templates/qanda/search.html
{% extends 'base.html' %}
{% load markdownify %}

{% block body %}
<h2>Search</h2>
<form class="search-form form-inline" method="get">
    <input class="form-control mr-2"
           type="search"
           placeholder="Search"
           name="q", value="{{ query }}">
    <button class="btn btn-primary" type="submit">Search</button>
</form>
{% if query %}
<h3>Results from search query '{{ query }}'</h3>
<ul class="list-unstyled search-results">
    {% for hit in hits %}
    <li>
        <a href="{% url 'qanda:question-detail' pk=hit.id %}">
            {{ hit.title }}
        </a>
        <div>
            {{ hit.question|markdownify|truncatewords_html:20 }}
        </div>
    </li>
    {% empty %}
    <li>No results</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Answerly{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Answerly</a>
    <button class="navbar-toggler" type="button"
        data-toggle="collapse" data-target="#navbarColor02"
        aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'qanda:ask' %}">Ask</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'qanda:index' %}">Today's questions</a>
        </li>
        </ul>
        <form class="form-inline my-2 mr-4 my-lg-0"
                action="{% url 'qanda:question-search' %}"
                method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if user.is_authenticated %}
            <a class="nav-link btn btn-secondary" href="{% url 'user:logout' %}">Logout</a>
        {% else %}
            <a class="nav-link btn btn-secondary mr-2" href="{% url 'user:login' %}">Login</a>
            <a class="nav-link btn btn-secondary" href="{% url 'user:register' %}">Register</a>
        {% endif %}
    </div>
    </nav>
    <div class="container main-content">
        {% block body %}{% endblock %}
    </div>
    <footer class="footer">
      <div class="container">
          <span class="text-muted">Arsen Losenko, {% now "Y" %}
              UI made with <a href="https://bootswatch.com/lumen/" target="_blank">Lumen Theme</a>
          </span>
      </div>
    </footer>
</body>
</html>

user/templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="col-sm-12">
    <h1>Register for MyQA</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">
            Register
        </button>
    </form>
</div>
{% endblock %}